apiVersion: v2
name: retool
description: A Helm chart for Kubernetes
type: application
version: 6.0.7
maintainers:
  - name: Retool Engineering
    email: engineering+helm@retool.com
dependencies:
  - name: postgresql
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: retool-temporal-services-helm
    version: 1.1.2
    condition: retool-temporal-services-helm.enabled,workflows.enabled
